name: qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-seurat=5.1.0
  - r-devtools=2.4.5
  - r-cairo
  - r-biocmanager=1.30.23
  - bioconda::bioconductor-scater
  - bioconda::bioconductor-singlecellexperiment==1.24.0
  - bioconda::bioconductor-iranges==2.36.0
