name: single_seurat
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-seurat=5.1.0
  - r-devtools=2.4.5
  - r-cairo
  - bioconductor-pcatools==2.14.0
  - bioconda::bioconductor-singlecellexperiment==1.24.0
  - bioconda::bioconductor-iranges==2.36.0
