name: annotation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-seurat=5.1.0
  - r-biocmanager=1.30.23
  - bioconductor-celldex=1.12.0
  - bioconductor-singler=2.4.0
  - bioconductor-singlecellexperiment=1.24.0
  - bioconductor-iranges=2.36.0
  - r-cairo
