name: "starsolo"
description: Create a counts matrix for single-cell data using STARSolo, handling cell barcodes and UMI information.
keywords:
  - align
  - count
  - genome
  - reference
tools:
  - "starsolo":
      description: "Mapping, demultiplexing and quantification for single cell RNA-seq."
      homepage: "https://github.com/alexdobin/STAR/"
      documentation: "https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md"
      doi: "10.1101/2021.05.05.442755"
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information.
        e.g. [ id:'test' ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 2 for paired-end data
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information.
        e.g. [ id:'test' ]
  - log_final:
      type: file
      description: STAR final log file
      pattern: "*Log.final.out"
  - log_out:
      type: file
      description: STAR lot out file
      pattern: "*Log.out"
  - log_progress:
      type: file
      description: STAR log progress file
      pattern: "*Log.progress.out"
  - summary:
      type: file
      description: STARSolo metrics summary CSV file.
      pattern: "*/Gene/Summary.csv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@brunapilotto"
